FROM ubuntu:22.04

# # [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends \
#         net-tools python3 python3-pip \
#         curl gnupg nmap babeltrace libbabeltrace-dev \
#         python3-babeltrace less git
